### ISSUE TITLE
how to remove installed minecraft file and t launcher !

### ISSUE THREAD

**Issue by piyus-01** [leanwell/TLauncher#3]
i am in debian 'bookworm' and now as i run the  (.sh)  file you have provied . but now i dont want to play the game so i have to remove it completely . what should i do in order to remove the installed minecraft version which was of 777Mbs. and the t launcher .

**Comment by leanwell** [comment]
> i am in debian 'bookworm' and now as i run the (.sh) file you have provied . but now i dont want to play the game so i have to remove it completely . what should i do in order to remove the installed minecraft version which was of 777Mbs. and the t launcher .

did you run it with `sudo`? if yes, you need to open file manager with administrator privilege and locate to /root/
delete `.minecraft` and `.tlauncher` folders
